alter table public.songs add column if not exists chart_rank integer;
alter table public.songs add column if not exists chart_source text;
alter table public.songs add column if not exists chart_updated_at timestamptz;
create unique index if not exists songs_provider_track_unique_idx on public.songs(provider_track_id);

insert into public.artists(slug,name,country,featured) values
('lenin-ramirez','Lenin Ramírez','México',true),('el-bogueto','El Bogueto','México',true),('shakira','Shakira','Colombia',true),('herencia-de-grandes','Herencia De Grandes','México',false),('karol-g','KAROL G','Colombia',true),('julion-alvarez','Julión Álvarez y su Norteño Banda','México',true),('emmanuel-cortes','Emmanuel Cortes','México',false),('anuel-aa','Anuel AA','Puerto Rico',true),('lil-naay','Lil Naay','República Dominicana',false),('el-alfa','El Alfa','República Dominicana',true),('ele-a-el-dominio','Ele A El Dominio','Puerto Rico',false),('los-dos-de-tamaulipas','Los Dos de Tamaulipas','México',true),('omar-courtz','Omar Courtz','Puerto Rico',true),('monchy-alexandra','Monchy & Alexandra','República Dominicana',true),('de-la-ghetto','De La Ghetto','Puerto Rico',true),('espinoza-paz','Espinoza Paz','México',true),('vilma-palma','Vilma Palma e Vampiros','Argentina',true),('romeo-santos','Romeo Santos','Estados Unidos',true),('los-dareyes','Los Dareyes De La Sierra','México',false),('grupo-firme','Grupo Firme','México',true),('los-bukis','Los Bukis','México',true),('danny-ocean','Danny Ocean','Venezuela',true),('bad-bunny','Bad Bunny','Puerto Rico',true),('j-balvin','J Balvin','Colombia',true),('plan-b','Plan B','Puerto Rico',true),('oscar-maydon','Oscar Maydon','México',true),('fuerza-regida','Fuerza Regida','Estados Unidos',true),('banda-blanca','Banda Blanca','Honduras',true),('luis-fonsi','Luis Fonsi','Puerto Rico',true),('queen','Queen','Reino Unido',false),('michael-jackson','Michael Jackson','Estados Unidos',false),('bruno-mars','Bruno Mars','Estados Unidos',true),('katy-perry','Katy Perry','Estados Unidos',false)
on conflict(slug) do update set name=excluded.name,country=excluded.country,featured=excluded.featured,active=true;

insert into public.songs(title,artist_name,artist_id,genre_id,provider,provider_track_id,thumbnail_url,duration_seconds,is_featured,is_honduras_hit,play_count,chart_rank,chart_source,chart_updated_at) values
('Todo Lo Fue','Lenin Ramírez',(select id from public.artists where slug='lenin-ramirez'),(select id from public.genres where slug='banda'),'youtube','search:lenin-ramirez-todo-lo-fue','',0,true,true,180,1,'YouTube Honduras',now()),
('Cuando No Era Cantante','El Bogueto & Yung Beef',(select id from public.artists where slug='el-bogueto'),(select id from public.genres where slug='reggaeton'),'youtube','search:cuando-no-era-cantante-el-bogueto','',0,true,true,175,2,'YouTube Honduras',now()),
('Dai Dai','Shakira & Burna Boy',(select id from public.artists where slug='shakira'),(select id from public.genres where slug='pop'),'youtube','search:shakira-dai-dai','',0,true,true,170,3,'YouTube Honduras',now()),
('Ya Borracho','Herencia De Grandes',(select id from public.artists where slug='herencia-de-grandes'),(select id from public.genres where slug='banda'),'youtube','search:herencia-de-grandes-ya-borracho','',0,false,true,165,4,'YouTube Honduras',now()),
('BbY WOW','KAROL G, Judeline & rusowsky',(select id from public.artists where slug='karol-g'),(select id from public.genres where slug='pop'),'youtube','search:karol-g-bby-wow','',0,true,true,200,5,'YouTube Honduras',now()),
('Cero Empatía','Julión Álvarez y su Norteño Banda',(select id from public.artists where slug='julion-alvarez'),(select id from public.genres where slug='rancheras'),'youtube','search:julion-alvarez-cero-empatia','',0,true,true,160,6,'YouTube Honduras',now()),
('Amor','Emmanuel Cortes',(select id from public.artists where slug='emmanuel-cortes'),(select id from public.genres where slug='baladas'),'youtube','search:emmanuel-cortes-amor','',0,false,true,155,7,'YouTube Honduras',now()),
('Las más bonitas son p#tas','Anuel AA',(select id from public.artists where slug='anuel-aa'),(select id from public.genres where slug='reggaeton'),'youtube','search:anuel-las-mas-bonitas','',0,false,true,150,8,'YouTube Honduras',now()),
('UNA BABY EN SANTIAGO','Lil Naay',(select id from public.artists where slug='lil-naay'),(select id from public.genres where slug='reggaeton'),'youtube','search:lil-naay-una-baby-en-santiago','',0,false,true,145,9,'YouTube Honduras',now()),
('PANTI Y COLALE 2.0','El Alfa, De La Ghetto, Zion y más',(select id from public.artists where slug='el-alfa'),(select id from public.genres where slug='reggaeton'),'youtube','search:panti-y-colale-2','',0,true,true,140,10,'YouTube Honduras',now()),
('PERRA','Lil Naay',(select id from public.artists where slug='lil-naay'),(select id from public.genres where slug='reggaeton'),'youtube','search:lil-naay-perra','',0,false,true,135,11,'YouTube Honduras',now()),
('No Contesta','Ele A El Dominio',(select id from public.artists where slug='ele-a-el-dominio'),(select id from public.genres where slug='reggaeton'),'youtube','search:ele-a-el-dominio-no-contesta','',0,false,true,130,12,'YouTube Honduras',now()),
('Ayúdame','Los Dos de Tamaulipas',(select id from public.artists where slug='los-dos-de-tamaulipas'),(select id from public.genres where slug='banda'),'youtube','search:los-dos-de-tamaulipas-ayudame','',0,true,true,125,13,'YouTube Honduras',now()),
('POR SI MAÑANA NO ESTOY','Omar Courtz',(select id from public.artists where slug='omar-courtz'),(select id from public.genres where slug='reggaeton'),'youtube','search:omar-courtz-por-si-manana-no-estoy','',0,true,true,120,14,'YouTube Honduras',now()),
('Hoja en Blanco','Monchy & Alexandra',(select id from public.artists where slug='monchy-alexandra'),(select id from public.genres where slug='bachata'),'youtube','search:monchy-alexandra-hoja-en-blanco','',0,true,true,115,15,'YouTube Honduras',now()),
('Dices','De La Ghetto',(select id from public.artists where slug='de-la-ghetto'),(select id from public.genres where slug='reggaeton'),'youtube','search:de-la-ghetto-dices','',0,false,true,110,16,'YouTube Honduras',now()),
('Lo Intentamos','Espinoza Paz',(select id from public.artists where slug='espinoza-paz'),(select id from public.genres where slug='rancheras'),'youtube','search:espinoza-paz-lo-intentamos','',0,true,true,105,17,'YouTube Honduras',now()),
('Bye Bye','Vilma Palma e Vampiros',(select id from public.artists where slug='vilma-palma'),(select id from public.genres where slug='rock-espanol'),'youtube','search:vilma-palma-bye-bye','',0,true,true,100,18,'YouTube Honduras',now()),
('Necio','Romeo Santos & Carlos Santana',(select id from public.artists where slug='romeo-santos'),(select id from public.genres where slug='bachata'),'youtube','search:romeo-santos-necio','',0,true,true,95,19,'YouTube Honduras',now()),
('MATCHA','Los Dareyes De La Sierra',(select id from public.artists where slug='los-dareyes'),(select id from public.genres where slug='banda'),'youtube','search:los-dareyes-matcha','',0,false,true,90,20,'YouTube Honduras',now()),
('Al Final Del Día','Grupo Firme',(select id from public.artists where slug='grupo-firme'),(select id from public.genres where slug='banda'),'youtube','search:grupo-firme-al-final-del-dia','',0,true,false,86,null,null,null),
('Tus Mentiras','Los Bukis',(select id from public.artists where slug='los-bukis'),(select id from public.genres where slug='baladas'),'youtube','search:los-bukis-tus-mentiras','',0,true,false,84,null,null,null),
('El Próximo Viernes','Espinoza Paz',(select id from public.artists where slug='espinoza-paz'),(select id from public.genres where slug='rancheras'),'youtube','search:espinoza-paz-el-proximo-viernes','',0,false,false,80,null,null,null),
('Imitadora','Romeo Santos',(select id from public.artists where slug='romeo-santos'),(select id from public.genres where slug='bachata'),'youtube','search:romeo-santos-imitadora','',0,true,false,78,null,null,null),
('Diles','Bad Bunny, Ozuna, Farruko, Arcángel & Ñengo Flow',(select id from public.artists where slug='bad-bunny'),(select id from public.genres where slug='reggaeton'),'youtube','search:bad-bunny-diles','',0,true,false,95,null,null,null),
('LA CANCIÓN','J Balvin & Bad Bunny',(select id from public.artists where slug='j-balvin'),(select id from public.genres where slug='reggaeton'),'youtube','search:j-balvin-la-cancion','',0,true,false,96,null,null,null),
('Es un Secreto','Plan B',(select id from public.artists where slug='plan-b'),(select id from public.genres where slug='reggaeton'),'youtube','kBdo_4yFons','https://i.ytimg.com/vi/kBdo_4yFons/hqdefault.jpg',0,true,false,100,null,null,null),
('Tu Boda','Oscar Maydon & Fuerza Regida',(select id from public.artists where slug='oscar-maydon'),(select id from public.genres where slug='banda'),'youtube','_ymicn0_GYc','https://i.ytimg.com/vi/_ymicn0_GYc/hqdefault.jpg',0,true,false,110,null,null,null),
('Me Rehúso','Danny Ocean',(select id from public.artists where slug='danny-ocean'),(select id from public.genres where slug='pop'),'youtube','aDCcLQto5BM','https://i.ytimg.com/vi/aDCcLQto5BM/hqdefault.jpg',0,true,false,125,null,null,null),
('Despacito','Luis Fonsi ft. Daddy Yankee',(select id from public.artists where slug='luis-fonsi'),(select id from public.genres where slug='reggaeton'),'youtube','kJQP7kiw5Fk','https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg',282,true,false,118,null,null,null),
('Sopa de Caracol','Banda Blanca',(select id from public.artists where slug='banda-blanca'),(select id from public.genres where slug='punta'),'youtube','search:banda-blanca-sopa-de-caracol','',0,true,false,130,null,null,null),
('Bohemian Rhapsody','Queen',(select id from public.artists where slug='queen'),(select id from public.genres where slug='clasicos'),'youtube','fJ9rUzIMcZQ','https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg',354,false,false,65,null,null,null),
('Billie Jean','Michael Jackson',(select id from public.artists where slug='michael-jackson'),(select id from public.genres where slug='clasicos'),'youtube','Zi_XLOBDo_Y','https://i.ytimg.com/vi/Zi_XLOBDo_Y/hqdefault.jpg',294,false,false,70,null,null,null),
('Uptown Funk','Mark Ronson ft. Bruno Mars',(select id from public.artists where slug='bruno-mars'),(select id from public.genres where slug='pop'),'youtube','OPf0YbXqDm0','https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg',270,true,false,90,null,null,null),
('Roar','Katy Perry',(select id from public.artists where slug='katy-perry'),(select id from public.genres where slug='pop'),'youtube','CevxZvSJLk8','https://i.ytimg.com/vi/CevxZvSJLk8/hqdefault.jpg',270,false,false,60,null,null,null)
on conflict(provider_track_id) do update set title=excluded.title,artist_name=excluded.artist_name,artist_id=excluded.artist_id,genre_id=excluded.genre_id,thumbnail_url=excluded.thumbnail_url,duration_seconds=excluded.duration_seconds,is_featured=excluded.is_featured,is_honduras_hit=excluded.is_honduras_hit,chart_rank=excluded.chart_rank,chart_source=excluded.chart_source,chart_updated_at=excluded.chart_updated_at,active=true;
